version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: docker:git
    steps:
      - checkout
      - run: echo "Initial testing should be here"
  jenkins:
    docker:
      - image: docker:git
    steps:
      - deploy:
          name: Call Jenkins to continue workflow
          command: |
            job_name='TEST+docker-node+CI+Package_Docker'
            apk add --no-cache curl tcptraceroute
            auth="${GITHUB_USER}:${GITHUB_TOKEN_JENKINS}"
            echo "Auth: $auth"
            build_cause='circleCI'
            echo "URL: ${JENKINS_URL}"
            tcptraceroute -h
            tcptraceroute jenkins.one.wiser.com
            crumb=$(curl -s -u ${auth} ${JENKINS_URL}/crumbIssuer/api/xml?'xpath=concat(//crumbRequestField,":",//crumb)')
            echo "Crumb: $crumb"
            curl -X POST -H "${crumb}" "${JENKINS_URL}/job/${job_name}/build?token=${JENKINS_JOB_TOKEN}&cause=${build_cause}" \
              --user ${auth}

workflows:
  version: 2
  node_workflow:
    jobs:
      - build
      - jenkins:
          context: org-global
